name: Go Application Deployment

on:
  push:
    branches:
      - main

env:
  DO_DROPLET_IP: 64.255.84.218
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Set up Go
      #   uses: actions/setup-go@v3
      #   with:
      #     go-version: 1.20.5

      # - name: Build application
      #   run: go build -v ./...

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DO_DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mv go.mod /opt/goapps/
            mv .env /opt/goapps/
            sudo pm2 restart MYPLANTBACKEND --update-env            
